### PR TITLE
Partial dependency updates and cleanup

### PR DESCRIPTION
**Pull request by FrankHassanabad**
* Deleted ds store files from Mac
  * Added gitignore file
  * Updated Android to latest cordova
  * Added README.md with simple build instructions
  * Updated package.json description
  * Removed plugins and platform directories in favor of cordova prepare

### CODE REVIEW

**Comment by FrankHassanabad** [comment]
Hello,

I am looking to update this project and complete some tasks for the next week or two if that is alright with everyone on the team.

This looks like an initially large PR as I am deleting a lot of files, but my game plan is mostly cleanup tasks to start with and dependency updates.  I don't know if everyone communicates via slack or another chat but if so I can do chat for any questions.

If you could look at the updated Readme file and see if this new way with `cordova prepare` works and deploys correctly as a test I would be very happy.  On my Android emulator it looks to work correctly.

Here is a public Trello board I created with tasks I am hoping to accomplish in a short time frame:
https://trello.com/b/YqNcvPGj/landpks-mobile-application

Ignore the backlog if you want, as I am only working towards what's in the sprint as of right now.

**Comment by ricksaltzman** [comment]
Hi Frank,

Thought I'd offer help if needed as I run the project for LandPKS.  I'm interested to understand what you are planning and if any of it might be helpful to fold back into LPKS.

Cheers,
rick.saltzman@gmail.com

**Comment by FrankHassanabad** [comment]
Hi Rick,

Take a look at my Trello board and in particular just the sprint column.  I am interested in the short term helping to upgrade the dependencies, add a linter, and maybe break out the code into testable units.

Basically a cleanup, standardization, and upgrade.

**Comment by ricksaltzman** [comment]
I've looked at the Trello board, give me a shout at 720 628 5545 and let's chat a bit before I dive in.  We have more than a little test coverage you might be able to leverage.

**Pull request closed without merging**
